import * as React from "react";
// generated-product-shell.mjs is a byte-for-byte copy of ../../../scripts/product-shell.mjs,
// written fresh by scripts/build.mjs on every build (see that file for why: TypeScript's
// rootDir cannot import a file that lives outside design-system/src). Never hand-edit it.
import { renderProductShellFooter, renderProductShellHeader } from "./generated-product-shell.mjs";
import { rawElementFromHtml } from "./rawElement";

export interface ShellHeaderProps {
  /** Key of the nav link to mark as the current page (e.g. "research", "verify"). */
  active?: string;
  /** Renders the live broker-status id/class the homepage's JS hydrates. Static pages omit it. */
  dynamicStatus?: boolean;
}

/**
 * The site's real header chrome (`<header class="cc-shell">`), rendered from the exact same
 * scripts/product-shell.mjs used to build every page on canlicapital.com. This component
 * does not re-author any markup: it calls the real render function at build/render time and
 * hands the resulting HTML string to a React element with the same tag and attributes, so the
 * output is byte-identical to what the site itself produces for the same inputs. Content is
 * generated by a trusted, dependency-free first-party module (not user input), which is what
 * makes rendering it via innerHTML safe here.
 */
export function ShellHeader({ active = "", dynamicStatus = false }: ShellHeaderProps): React.ReactElement {
  return rawElementFromHtml(renderProductShellHeader({ active, dynamicStatus }));
}

export interface ShellFooterProps {}

/** The site's real footer chrome (`<footer class="cc-footer">`), rendered the same way as ShellHeader. */
export function ShellFooter(_props: ShellFooterProps = {}): React.ReactElement {
  return rawElementFromHtml(renderProductShellFooter());
}
