// =============================================================================
// CANLI CAPITAL / scripts/build-papers.mjs
// -----------------------------------------------------------------------------
// Renders every research document in public/research/*.md into a real, indexable
// HTML page at /research/<slug>, and rebuilds sitemap.xml from what exists on disk.
//
// WHY THIS EXISTS. The documents were already written -- 33 of them, cited,
// specific, the genuine output of the programme -- and they were served as raw
// .md. A raw markdown file has no <title>, no meta description, no canonical, no
// structured data and no author. Search engines could not read them as documents,
// and the sitemap listed six URLs, none of which was a paper. The largest
// discoverability problem on this site was never a shortage of content; it was
// that the content had no HTML to be found in.
//
// Two rules this script keeps:
//   1. It never invents scientific metadata. Title and description are taken FROM the
//      document. A hash-bound source may use the audited presentation-only short-title
//      registry for `<title>` without changing its H1, citations, schema, or source bytes.
//      A document that carries neither is REPORTED, not guessed at.
//   2. The sitemap is derived from generated files, never hand-maintained. The
//      hand-maintained one is how six URLs came to stand for thirty-nine.
// =============================================================================

import { createHash } from "node:crypto";
import { readFileSync, writeFileSync, readdirSync, mkdirSync, existsSync, rmSync } from "node:fs";
import { dirname, resolve, basename } from "node:path";
import { fileURLToPath } from "node:url";
import { marked } from "marked";
import {
  IMMUTABLE_PAPER_SHORT_TITLES,
  IMMUTABLE_PAPER_SOURCES,
} from "./paper-presentation.mjs";
import {
  renderProductShellFooter,
  renderProductShellHeader,
  renderProductShellStylesheet,
} from "./product-shell.mjs";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const SOURCE_DIR = resolve(ROOT, "public/research");
const CITATION_DIR = resolve(SOURCE_DIR, "citations");
const OUT_DIR = resolve(ROOT, "research");
const ORIGIN = "https://canlicapital.com";
const AUTHOR = "Arhan Canli";
const PUBLISHER = "Canli Capital";
// Every document in this corpus was first published during the 2026 programme.  Scholar accepts
// a year as the publication date, and a truthful year is preferable to manufacturing day-level
// precision that the original markdown files do not carry.  If the corpus crosses a calendar
// year, make publication year explicit per document rather than deriving it from build time.
const PUBLICATION_YEAR = "2026";
const sha256 = (text) => createHash("sha256").update(text).digest("hex");

const archivalPaperRoutes = () => {
  const registryPath = resolve(ROOT, "public/glassbox/external_publication_registry.json");
  if (!existsSync(registryPath)) return [];
  const registry = JSON.parse(readFileSync(registryPath, "utf8"));
  return registry.sleeves.map((paper) => {
    const originalRoute = `/${paper.bundle_manifest.replace(/\/bundle_manifest\.json$/, "/paper")}`;
    const wrapperRoute = originalRoute.replace(/\/paper$/, "");
    const originalFile = resolve(ROOT, "public", `${originalRoute.slice(1)}.html`);
    const wrapperFile = resolve(ROOT, `${wrapperRoute.slice(1)}.html`);
    if (!existsSync(originalFile)) {
      throw new Error(`registered archival paper has no public HTML: ${originalRoute}`);
    }
    if (!existsSync(wrapperFile)) {
      throw new Error(`registered archival paper has no current-shell wrapper: ${wrapperRoute}`);
    }
    return {
      title: paper.title,
      route: wrapperRoute,
      originalRoute,
      loc: `${ORIGIN}${wrapperRoute}`,
      priority: "0.7",
      changefreq: "monthly",
    };
  });
};

// Measurement pages are generated by build-measurements.mjs, which runs first. Read from disk so
// the sitemap counts what exists rather than what someone remembered to add.
const measurementRoutes = () => {
  const dir = resolve(ROOT, "measurements");
  if (!existsSync(dir)) return [];
  return readdirSync(dir)
    .filter((name) => name.endsWith(".html"))
    .map((name) => ({
      loc: `${ORIGIN}/measurements/${name.slice(0, -5)}`,
      priority: "0.7",
      changefreq: "weekly",
    }));
};

const trialRoutes = () => {
  const dir = resolve(ROOT, "trials");
  if (!existsSync(dir)) return [];
  const indexPath = resolve(ROOT, "public/glassbox/trial-packets/index.json");
  if (!existsSync(indexPath)) {
    throw new Error("trial pages exist but their packet index is missing");
  }
  const index = JSON.parse(readFileSync(indexPath, "utf8"));
  return index.packets
    .filter((packet) => packet.complete === true)
    .map((packet) => {
      const builtFile = resolve(dir, `${packet.hypothesis_key}.html`);
      if (!existsSync(builtFile)) {
        throw new Error(`complete trial packet has no public HTML: ${packet.hypothesis_key}`);
      }
      return {
        loc: `${ORIGIN}/trials/${packet.hypothesis_key}`,
        priority: "0.6",
        changefreq: "monthly",
      };
    });
};

const STATIC_ROUTES = [
  { path: "/", priority: "1.0", changefreq: "weekly" },
  { path: "/systems", priority: "0.8", changefreq: "weekly" },
  { path: "/performance", priority: "0.8", changefreq: "weekly" },
  { path: "/progress", priority: "0.8", changefreq: "weekly" },
  { path: "/research", priority: "0.9", changefreq: "weekly" },
  { path: "/open", priority: "0.8", changefreq: "weekly" },
  { path: "/measurements", priority: "0.9", changefreq: "weekly" },
  { path: "/trials", priority: "0.9", changefreq: "weekly" },
  { path: "/verify", priority: "0.9", changefreq: "weekly" },
  { path: "/review", priority: "0.8", changefreq: "weekly" },
  { path: "/foundry", priority: "0.8", changefreq: "weekly" },
  { path: "/founder", priority: "0.7", changefreq: "monthly" },
  { path: "/methodology", priority: "0.9", changefreq: "weekly" },
  { path: "/tools/deflated-sharpe", priority: "0.9", changefreq: "weekly" },
  { path: "/tools/evidence-chain", priority: "0.9", changefreq: "weekly" },
  { path: "/tools/trial-accounting", priority: "0.9", changefreq: "weekly" },
];

// =============================================================================
// TAXONOMY
// -----------------------------------------------------------------------------
// Eighty documents served as a flat alphabetical list is eighty orphans. A reader
// looking for "crypto funding carry research" has no route in, and neither does a
// crawler: there is nothing linking related work together, so nothing signals what
// this body of work is ABOUT.
//
// These clusters are DERIVED from the corpus, not invented for it — the vocabulary
// below was built by counting what the titles and descriptions actually say, and
// every hub carries the real descriptions of its members rather than a keyword
// list. A hub with nothing on it but links is a doorway page, deserves to be
// treated as one, and would undo the rest of this.
// =============================================================================

const KINDS = [
  { slug: "killed-candidates", label: "Killed candidates", match: (s) => s.startsWith("kill-"),
    blurb: "Every strategy that failed, published in full with the numbers it died on. Almost nobody publishes these, which is exactly why they are here: a kill log is a table, a paper is the reasoning another researcher can use." },
  { slug: "literature-reviews", label: "Literature reviews", match: (s) => s.startsWith("literature-"),
    blurb: "What the published evidence actually supports for each mechanism, with citations, and where our reading of it stops." },
  { slug: "feasibility-protocols", label: "Feasibility protocols", match: (s) => s.endsWith("-feasibility"),
    blurb: "Whether a mechanism can be tested at all — point-in-time data lineage, execution realism and document coverage — decided before any return data is opened." },
  { slug: "pre-registrations", label: "Pre-registrations", match: (s) => s.startsWith("prereg-"),
    blurb: "Locked specifications committed before measurement: universe, signal, horizon, costs and the pass/fail criteria, fixed in writing so the result cannot be chosen after the fact." },
  { slug: "corrections", label: "Corrections", match: (s) => s.includes("correction"),
    blurb: "Published figures we withdrew, and why. A correction that is part of the record is worth more than a number that was never wrong in public." },
  { slug: "engineering-foundations", label: "Engineering foundations", match: () => true,
    blurb: "The machinery underneath the research: execution realism, borrow and financing replay, corporate-action lifecycle, and the quality contracts that gate what gets published." },
];

const SUBJECTS = [
  { slug: "equities", label: "Equities", pattern: /equit|stock|momentum|earnings|10-k|filing|sec |issuer/i,
    blurb: "Cross-sectional equity research: momentum construction, quality and value replication on a survivorship-free universe, and the filing-derived signals tested against it." },
  { slug: "crypto", label: "Crypto", pattern: /crypto|perp|funding|bitcoin|btc|stablecoin|binance/i,
    blurb: "Perpetual-futures funding carry, basis, venue structure and stablecoin dislocation — the sleeve family where this book has the longest live record." },
  { slug: "options-and-volatility", label: "Options and volatility", pattern: /option|volatilit|dispersion|variance|gamma/i,
    blurb: "Variance risk premium, index-versus-constituent dispersion and dealer positioning: mechanisms that are well documented and expensive to implement honestly." },
  { slug: "rates-and-treasuries", label: "Rates and treasuries", pattern: /rates|treasury|fomc|yield|auction|swap/i,
    blurb: "Auction concession, pre-FOMC drift, swap-spread dislocation and curve carry — including the identities that turned out not to be observable as pre-registered." },
  { slug: "credit", label: "Credit", pattern: /credit|bond|etf nav|fallen angel|municipal/i,
    blurb: "Bond-ETF NAV dislocation, fallen-angel flow and credit-equity relative value, and the licensed-data boundaries that gate them." },
  { slug: "commodities", label: "Commodities", pattern: /commodit|petroleum|natural gas|oil|inventory|eia/i,
    blurb: "Inventory surprise, storage and weather: official point-in-time vintages, first-release capture, and what happens to a seasonal signal net of cost." },
  { slug: "event-driven", label: "Event-driven", pattern: /merger|spin-?off|tender|arbitrage|13d|repurchase|reconstitution/i,
    blurb: "Merger arbitrage, spin-off dislocation, tender offers and activist escalation — mechanisms whose feasibility turns on what regulatory filings actually contain." },
  { slug: "macro-surprise", label: "Macro surprise", pattern: /cpi|inflation|macro|surprise|payroll/i,
    blurb: "Point-in-time macro releases traded as cross-sectional spreads, and the vintage discipline that makes the surprise real rather than hindsight." },
  { slug: "execution-and-market-structure", label: "Execution and market structure", pattern: /execution|borrow|financing|corporate action|market status|fill|slippage/i,
    blurb: "Borrow availability and fees, financing, corporate actions, market-status replay and fill modelling — the costs that decide whether a paper edge survives contact." },
];


// =============================================================================
// HUB ESSAYS
// -----------------------------------------------------------------------------
// A hub is a page that should rank for its subject, and a link list under one
// paragraph is a doorway page however good the links are. Each hub therefore
// opens with genuine subject content: what the mechanism is, what the published
// evidence supports, and what THIS book found — which is usually less than the
// literature would suggest and is written that way.
//
// Written per hub, never templated. A verifier check enforces that: no paragraph
// may appear on two hubs, because the moment one can, these become boilerplate
// with the subject noun swapped and they would deserve to rank for nothing.
// =============================================================================
const HUB_ESSAYS = {
  "killed-candidates": [
    "A kill file is the paper nobody writes. A strategy is tested, it does not work, and the result goes in a drawer — so the same idea is tested again next year by someone else who had no way of knowing. That silence is not modesty; it is what makes the published record of quantitative finance systematically optimistic, because the surviving results are the ones that happened to clear a threshold and the failures that surrounded them were never counted.",
    "The statistical cost of that silence has a name. When many candidates are tried and one is reported, the reported figure has to be deflated by how many were tried, and a Sharpe ratio that looks convincing at one trial is unremarkable at a hundred. That deflation is only possible if the trial count is honest, which is why every kill here is numbered and counted against a public ledger rather than quietly discarded. A kill is not a failure to be minimised. It is the denominator.",
    "What this collection shows is how much of the accessible ground is already dead. Named equity factors, cross-sectional and time-series construction on crypto perpetuals, seasonality, positioning, insider clusters, curve carry, inventory effects: tested, and killed on the numbers recorded in each file. Nearly every idea that is cheap to test has been tested by someone with more data, and the ones that survive on this book's own evidence are few and modest.",
    "Each document names the specific number the candidate died on, the window it was measured over, and what would have had to be true for it to survive. That is the part a kill log cannot give you. A table saying REJECTED tells you the outcome; a paper tells you the reasoning, which is the only part another researcher can use — either to avoid repeating the work, or to show that the reasoning was wrong."
  ],
  "literature-reviews": [
    "Before a mechanism is tested here it is read. A literature review in this collection asks a narrow question: does the published evidence describe an effect that is economically motivated, replicated outside its original sample, and still present after the paper that named it — and if so, what exactly is the claim, in units precise enough to be pre-registered against.",
    "That last requirement does most of the work. A great deal of published finance describes an effect in terms that cannot be turned into a specification: the universe drifts, the horizon is chosen after the fact, the cost assumption is absent, or the data used to establish it was restated afterwards. A mechanism that cannot be stated as a testable identity is not a candidate here, however well cited it is, and several reviews end at exactly that point.",
    "Each review states where our reading of the evidence stops. That boundary matters more than a verdict: an effect that is well documented in institutional US equities from 1990 to 2010 is not thereby documented in crypto perpetuals in 2026, and a review that quietly transfers a finding across that gap is doing the reader more harm than one that reaches no conclusion.",
    "These reviews exist to be used against us. If one misreads a paper, overstates a replication, or ignores a contrary result, that is checkable from the citations, and it is checkable before any capital or any trial budget has been spent on the idea. Reading first is cheaper than measuring first, and it is the only stage of this process where being wrong costs nothing."
  ],
  "feasibility-protocols": [
    "A feasibility protocol asks whether a mechanism can be tested at all, and it is decided before any return data is opened. Three things have to be true: the evidence must exist in a point-in-time form, it must be extractable at a rate the identity assumes, and the resulting positions must be executable at a cost the mechanism can pay. If any one fails, the idea is not weak — it is unmeasurable here, and that is a different and more useful verdict.",
    "The order is deliberate. Opening return data is the expensive step, because it consumes a hypothesis from a finite budget and it can never be un-consumed: once a researcher has seen how a candidate performed, every subsequent choice about it is contaminated by that knowledge. Deciding feasibility first keeps the expensive step for candidates that could survive it.",
    "What these protocols found is not encouraging, and it is published anyway. Several mechanisms that are well documented in the literature turned out to be unobservable as specified — the gate asked for language that regulatory filings do not contain at the assumed rate, or applied one threshold across populations with different disclosure obligations. In every case the shortfall was in what the documents carry, not in the parser reading them, so no amount of engineering would have closed it.",
    "That distinction is the whole value of the stage. A gate that fails by a few points invites exactly one move — widen the detector until the number clears — and that is tuning a measurement to agree with a target. The protocols here compute what a perfect detector would reach before anyone touches the imperfect one, so the question is settled on arithmetic rather than on effort."
  ],
  "engineering-foundations": [
    "Most of what decides whether a research result survives contact with a market is not research. It is whether the borrow was available, whether the corporate action was applied, whether the financing was charged, whether the venue was open, and whether the fill price was one anybody could have got. These documents are about that layer, and it is where more published edges die than in the signal itself.",
    "The failures at this layer share a characteristic that makes them dangerous: they are silent and they flatter. An unapplied split turns a price series into a profit. A fill modelled at the mid earns a spread nobody paid. A backtest that ignores borrow shorts names that could not be shorted. None of these produce an error message; they produce a better number, which is why they survive review by people who are checking the strategy rather than the plumbing.",
    "So each foundation is a contract with a test behind it rather than a description. Execution realism, borrow and financing replay, corporate-action lifecycle and market-status handling are specified, and the specification is enforced by guards that are themselves mutation-tested — broken deliberately to confirm they fail, because a check that cannot fail is worse than no check at all.",
    "The same discipline applies to what these documents admit they cannot do. The cost model's one fully checkable component, crypto commission, matched exactly at 5.00 basis points against a modelled 5.0. The equity components could not be checked at all, because the recorded fills carry a padded limit price rather than a decision price — a fill that appears to beat it is beating the padding. That is published as a schema defect with a one-field fix, not smoothed over as a cost estimate."
  ],
  "equities": [
    "The cross-sectional equity factor is the most examined object in quantitative finance. Momentum, value, quality, profitability, issuance, low volatility and their many constructions have been documented, replicated, decayed and re-documented across decades of data by people with better data than this book has. That is the honest starting position: this is not virgin ground, and an edge found here is much more likely to be a construction artifact than a discovery.",
    "This research is run on a survivorship-free universe with point-in-time membership, because the alternative silently answers a different question. A backtest on today's index constituents is a backtest on companies that did not go bankrupt, and it will show a quality effect whether or not one exists. Filing-derived signals face a sharper version of the same problem: the date a fact was measured is not the date it was knowable, and a series stamped with the former trades on information from the future.",
    "What survived on this book's own evidence is narrow. A conventional cross-sectional momentum construction is the one equity sleeve that trades. Almost everything else tested here — the fifty-two-week high, post-earnings drift, gross profitability, book-to-price, net issuance, residual momentum, cross-sectional seasonality, insider purchase clusters, intraday reversal and positioning-derived signals — is published as a kill, with the number it died on.",
    "The enhancement work is equally unflattering and equally published: successive attempts to improve the surviving momentum construction returned nulls, which is evidence that the construction lever is close to exhausted rather than evidence that more effort is required. Where the remaining upside lies is stated plainly in the corrections and feasibility work: in new and independent sources of return, not in another rearrangement of the same inputs."
  ],
  "crypto": [
    "Perpetual futures carry a mechanism that has no equity analogue: a funding payment exchanged between longs and shorts at a fixed interval to hold the contract near spot. It is a real cash flow with a published rate, which makes carry in this market unusually well defined — you are not inferring a premium from returns, you are being paid one on a schedule, and the schedule is observable.",
    "That clarity is also the trap. Funding carry is a liquidity-provision trade wearing a yield's clothing: it pays steadily and loses violently in exactly the cascade that makes it pay. Its return distribution is dominated by rare observations, and a Sharpe ratio computed on a calm sample says almost nothing about the risk being taken. Any honest treatment of this sleeve has to separate what it earned from what it was exposed to, and this book's own decomposition of that separation is published.",
    "This is the sleeve family with the longest live record here, and it is also the one where the most has been killed. Dated basis, low-volatility construction, short-side time-series momentum, the variance risk premium, funding term structure and multi-venue funding differentials were each tested and each published as a null. The one construction that trades is the plain cross-sectional funding carry.",
    "Venue structure is treated as part of the mechanism rather than as an implementation detail, because in this market it is. Funding is a venue-specific quantity, the same instrument has different rates in different places, and a research result computed on one exchange's history may not be reproducible on another's. Multi-venue collection runs daily for that reason, and the boundaries of what has actually been collected are published rather than assumed."
  ],
  "options-and-volatility": [
    "The variance risk premium is among the best documented effects in finance: implied volatility exceeds subsequent realised volatility on average, across markets and across decades, and there is a coherent economic reason why someone would pay it. Index-versus-constituent dispersion is its cross-sectional cousin, and dealer hedging flow is the microstructural residue of both. None of these is a secret.",
    "They are, however, expensive to implement honestly, and that is where most of the published enthusiasm goes. Selling volatility is short convexity: the strategy earns a small premium repeatedly and gives it back in a single episode, so a backtest over any sample without such an episode is measuring the premium and not the risk. Add bid-ask spreads on options, the cost of delta hedging, and the assumption that a historical quote was executable, and a large fraction of the documented premium is gone before any of it is realised.",
    "The feasibility question here is unusually binding. A point-in-time option surface — open interest, quotes and the chain as it stood on a past date — is either a licensed vendor product or a reconstruction, and a reconstruction that begins recently cannot supply the years of observations a deflated result requires. That constraint has been measured against the admission contract rather than argued about, and the arithmetic decides before the idea does.",
    "So what is published in this cluster is mostly boundary work: what the mechanism is, what it would take to test it properly, the execution contracts that would have to hold, and the crypto variance premium tested and killed. That is a thinner result than the literature would suggest, and it is the accurate one for a book that will not price a strategy at quotes it could not have traded."
  ],
  "rates-and-treasuries": [
    "Rates research here concerns mechanisms with a scheduled cause: an auction that must be absorbed, a policy meeting that must be priced, a swap that must be funded against a deliverable. Effects with a known timetable are attractive because the event is unambiguous and cannot be discovered after the fact — you know when it happened before you know what it did.",
    "That advantage is smaller than it looks, because the timetable itself has a history and the history is often reconstructed. A calendar that is scraped today reflects revisions, cancellations and re-scheduling that were not known at the time, and a study anchored on it is anchored on a document that did not exist when the trade would have been placed. Auditing the provenance of the schedule turned out to be a larger piece of work than testing the effect, and it is published in that order.",
    "The treasury auction concession identity is the clearest result in this cluster and it is a negative one: it is not observable as it was pre-registered. That verdict is published in full rather than replaced by a version of the identity that happens to be measurable, because a specification adjusted until it fits the available data is no longer a pre-registration.",
    "The pre-FOMC announcement drift is at the opposite stage — pre-registered, with its universe, window and pass criteria fixed in writing before measurement, and its data readiness audited separately. Curve carry has been tested and killed. What remains open is stated as open, including the swap-spread work, where the free constant-maturity series was discontinued and the modern curve is a licensed product."
  ],
  "credit": [
    "Credit sits between two markets that price the same risk differently, which is why relative-value mechanisms keep appearing here: a bond ETF against its net asset value, a fallen angel against forced index selling, an issuer's spread against its own equity. Each is a basis, and each is a wager that two prices for one obligation will converge on a timetable.",
    "Every one of them is a liquidity-provision trade, and that fact dominates the risk. The basis is widest precisely when it is hardest to fund, so the position that looks most attractive on a screen is the one whose other side has just disappeared. Any treatment that measures the mean reversion without measuring what happens in the episodes is describing the payoff and not the trade.",
    "The binding constraint here is data rather than economics. The public print record is truncated by dissemination caps, so the trades a researcher can see are systematically the small ones; the issuer mapping, terms and rating histories that make a basis computable are licensed products. Where a public route exists it is published with its truncation named, and where it does not, the blocker is recorded as a spending decision rather than dressed as a research question.",
    "What that leaves in this cluster is the feasibility and infrastructure work: the bond-ETF dislocation protocol, the financing replay that decides whether a carry position is affordable, and the literature that motivates them. No credit sleeve trades in this book, and the reason is written down."
  ],
  "commodities": [
    "Commodity research here follows physical constraint rather than sentiment. Storage capacity, inventory levels, seasonal demand and the positioning of hedgers are quantities with an official point-in-time record, published on a schedule by agencies that also publish their revisions — which makes them unusually well suited to honest vintage discipline compared with most financial data.",
    "Vintage discipline is the entire methodological content of this cluster. An inventory figure exists in several versions: the first release, and every revision after it. A study that uses the current value is using a number that was not available for weeks, and because revisions are not random the resulting effect can be manufactured entirely by hindsight. Capturing the first release, and only the first release, is what makes a surprise a surprise.",
    "The results have been unkind. Inventory seasonality, cross-sectional futures carry and cross-asset carry were each tested and published as nulls. The hedging-pressure and storage-weather mechanisms are at the feasibility stage, and one of them is blocked on a free credential and the other on paid data — recorded as such rather than left ambiguous, because a blocker with a price is not the same thing as a result.",
    "The general lesson from this cluster is about cost rather than signal. Seasonal commodity effects tend to be real, small, and slower than their turnover implies; net of roll, spread and the calendar alignment that a twenty-four-hour market imposes on a business-day book, several survived as ideas and none survived as sleeves."
  ],
  "event-driven": [
    "Event-driven mechanisms trade a corporate action with a legal timetable: a spin-off, a merger, a tender offer, a repurchase, an activist stake. The appeal is that the event is discrete and its date is documented, so the study window is defined by a filing rather than chosen by a researcher — the single largest source of accidental hindsight in most backtests is closed before the work starts.",
    "The evidence, though, lives in regulatory documents, and this is where the cluster's most useful findings came from. A protocol that assumes a filing states something will fail if the disclosure rule that produced the filing never required it. Three separate mechanisms here failed for exactly that reason, and the failures are published together because the pattern is worth more than any of them individually.",
    "The pattern is that each protocol specified a language test where the identity needed a structural fact. A registration statement was asked to state distribution mechanics that were not settled on the day it was filed. A narrative disclosure was asked to name a counterparty that the rule requiring the disclosure never required naming. A deal study was asked to require one specific form when what it actually needed was a timestamp that several documents supply.",
    "So the redesign notes here name the document that would carry the evidence before they name any threshold, and they propose no threshold at all — because a threshold chosen after seeing which population clears it is selection, not specification. The event universe for spin-offs, for instance, turned out to be declared by the form type itself: a registration form filed to distribute securities to shareholders needs no sentence inside it to say so, and the count is metadata rather than extraction."
  ],
  "macro-surprise": [
    "A macro surprise is the gap between a release and what was expected of it, traded as a cross-sectional spread rather than as a directional bet. The mechanism is that different kinds of company are differently exposed to the same macro variable, so an inflation print that is a mild aggregate event can be a large relative one — and the relative version is measurable without taking a view on the level.",
    "Everything here turns on vintages. Macro series are revised, sometimes substantially, and the revised value is the one every convenient data source serves. A study that uses it is trading on a number that did not exist on the day of the trade, and the resulting effect can be entirely an artifact of the revision process. The point-in-time vintage lake this research runs on exists for that single reason, and the rule used to date each series is published with it.",
    "This is the mechanism behind one of the book's live sleeves, a point-in-time consumer-price-surprise size spread, which makes the cluster small but load-bearing. It is also where one of this book's published corrections lives: a missing release was found and the affected figures were withdrawn and restated in public rather than quietly re-run.",
    "That correction is the most useful document here. A research process is not judged by whether it makes errors — it will — but by whether an error that flatters is as likely to be found and published as one that does not. The missing-release note exists so that question has a concrete answer rather than an assurance."
  ],
  "execution-and-market-structure": [
    "This cluster is about the distance between a decision and a fill. Every strategy in this book generates a target position; what it actually earns depends on the spread it crossed, the fee it paid, the borrow it needed, the financing it was charged, whether the venue was open, and how long it waited. Those quantities are not a haircut applied at the end. They are part of the mechanism, and for slower and smaller signals they are most of it.",
    "The recurring finding is that costs are usually modelled as the wrong kind of quantity rather than at the wrong level. Latency represented as a flat basis-point addition is treated as a microstructure effect, but an order submitted after the close and filled at the next open is not crossing a spread — it is holding unhedged overnight exposure with a fat-tailed distribution. Getting the size of such a term right does not fix having the wrong term.",
    "What can and cannot be checked is published together. The one fully verifiable component, crypto commission, matched exactly: five basis points measured against five modelled. Equity slippage could not be computed at all, because the recorded fills carry a padded marketable limit rather than the decision price, so a fill that appears to beat it by half a percent is beating the padding. The conclusion drawn was that no cost parameter should move on that evidence and the recording schema should — one additional field turns an unanswerable question into a daily measurement.",
    "The borrow, financing, corporate-action and market-status contracts here exist so that this layer is specified rather than assumed, and each is enforced by a guard rather than by a convention. Where the answer is that the record cannot yet support a conclusion, that is published as the result, because a noisy estimate presented as a measurement is a worse outcome than an honest not yet."
  ]
};

function classify(slug, title, description) {
  const kind = KINDS.find((k) => k.match(slug));
  const text = `${title} ${description}`;
  const subjects = SUBJECTS.filter((s) => s.pattern.test(text));
  return { kind, subjects };
}

const escapeHtml = (value) =>
  String(value)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#39;");

/** Strip markdown emphasis/links/code so a heading or paragraph reads as plain prose. */
function toPlainText(markdown) {
  return markdown
    .replace(/`([^`]*)`/g, "$1")
    .replace(/\[([^\]]+)\]\([^)]*\)/g, "$1")
    .replace(/\*\*([^*]+)\*\*/g, "$1")
    .replace(/\*([^*]+)\*/g, "$1")
    .replace(/_{1,2}([^_]+)_{1,2}/g, "$1")
    .replace(/\s+/g, " ")
    .trim();
}

// Markdown source documents sometimes cite another public research source by its exported .md
// path. In rendered HTML that is paper navigation, so it must resolve to the canonical HTML route.
// The explicit unrendered-source link is added later by pageHtml and remains a true raw download.
const canonicalizeRenderedResearchLinks = (html) =>
  html.replace(/href="(\/research\/[^"]+?)\.md(#[^"]*)?"/g, 'href="$1$2"');

/**
 * Pull the title and description out of the document itself.
 *
 * The description is the first real PROSE paragraph. These documents open with a
 * metadata block of bold key/value lines ("**Reviewed:** ..."), which describes the
 * document rather than its finding and would make every search result look alike.
 */
function extractMeta(markdown, slug) {
  const lines = markdown.split("\n");
  const headingIndex = lines.findIndex((line) => /^#\s+/.test(line));
  const title = headingIndex >= 0 ? toPlainText(lines[headingIndex].replace(/^#\s+/, "")) : null;

  // A SEARCH RESULT HEADLINE IS NOT A DOCUMENT'S NAME. Twenty-three papers carry titles past the
  // 65 characters a result shows, because their real names are long and precise — "Managed-Futures
  // fast-trend / real-futures breadth (campaign): a killed candidate" is the right name for the
  // document and the wrong thing to truncate mid-word in a result. So a paper may declare
  // `**Short title:** …` and that is used for <title> ONLY. The H1, the Open Graph title and the
  // structured-data headline all keep the real name, so nothing is renamed and nobody arrives at a
  // document called something other than what it is. verify-papers.mjs enforces both halves.
  const shortTitleLine = lines.find((line) => /^\*\*Short title:\*\*/i.test(line.trim()));
  const shortTitle = shortTitleLine
    ? toPlainText(shortTitleLine.replace(/^\s*\*\*Short title:\*\*\s*/i, ""))
    : IMMUTABLE_PAPER_SHORT_TITLES[slug] ?? null;

  let description = null;
  const afterHeading = headingIndex >= 0 ? lines.slice(headingIndex + 1).join("\n") : markdown;
  for (const block of afterHeading.split(/\n\s*\n/)) {
    const text = block.trim();
    if (!text) continue;
    if (/^#{1,6}\s/.test(text)) continue;                      // heading
    if (/^[-*+]\s|^\d+\.\s|^>|^\||^```|^\|/.test(text)) continue; // list, quote, table, code
    if (/^\*\*[^*]+:\*\*/.test(text)) continue;                // the metadata block
    const plain = toPlainText(text);
    if (plain.length < 60) continue;
    if (plain.endsWith(":")) continue;
    description = fitDescription(plain);
    break;
  }
  return { title, shortTitle, description, slug, sources: IMMUTABLE_PAPER_SOURCES[slug] ?? [] };
}

const DESCRIPTION_MAX = 158;

/** Trim to something that survives a search result: whole sentences first, whole words second. */
function fitDescription(text) {
  if (text.length <= DESCRIPTION_MAX) return text;

  // Find sentence ENDS and slice from position zero, rather than matching sentence pieces and
  // gluing them. Two bugs came out of the matching approach, both visible only in a rendered
  // page: a decimal point read as a sentence ending truncated "net Sharpe -0.5926" to
  // "net Sharpe -0.", and once that was fixed the pieces no longer tiled the string, so a
  // description could START mid-number ("84. A construction-fitting artifact..."). Slicing from
  // zero cannot do either.
  let cut = -1;
  for (let i = 0; i < Math.min(text.length, DESCRIPTION_MAX); i += 1) {
    const ch = text[i];
    if (ch !== "." && ch !== "!" && ch !== "?") continue;
    const next = text[i + 1];
    // A period followed by a digit is a decimal point, not a sentence ending.
    if (next !== undefined && !/\s/.test(next)) continue;
    cut = i + 1;
  }
  if (cut >= 70) return text.slice(0, cut).trim();

  const clipped = text.slice(0, DESCRIPTION_MAX - 1);
  return `${clipped.slice(0, clipped.lastIndexOf(" ")).trimEnd()}\u2026`;
}

// A title is truncated in results around 65 characters, and the site name is the least
// informative part of it. Drop the suffix rather than the subject when they do not both fit.
const TITLE_MAX = 65;
const SUFFIX = ` \u2014 ${PUBLISHER}`;

function fitTitle(title) {
  return title.length + SUFFIX.length <= TITLE_MAX ? `${title}${SUFFIX}` : title;
}

function citationKey(slug) {
  return `canli2026${slug.replace(/[^a-z0-9]/g, "")}`;
}

function bibtexValue(value) {
  return value
    .replace(/\\/g, "\\textbackslash{}")
    .replace(/([{}%&#_$])/g, "\\$1");
}

function bibtex(paper) {
  return `@techreport{${citationKey(paper.slug)},
  author      = {Canli, Arhan},
  title       = {${bibtexValue(paper.title)}},
  institution = {Canli Capital},
  type        = {Open quantitative research report},
  year        = {${PUBLICATION_YEAR}},
  url         = {${ORIGIN}/research/${paper.slug}}
}\n`;
}

function pageHtml({ title, shortTitle, description, slug, body, sourceFile, sourceSha256, sources = [], related = "" }) {
  const url = `${ORIGIN}/research/${slug}`;
  const jsonLd = {
    "@context": "https://schema.org",
    "@type": "ScholarlyArticle",
    headline: title,
    description,
    url,
    inLanguage: "en",
    isAccessibleForFree: true,
    datePublished: PUBLICATION_YEAR,
    author: {
      "@type": "Person",
      "@id": `${ORIGIN}/#arhan-canli`,
      name: AUTHOR,
      jobTitle: "Founder and Quantitative Researcher",
      url: `${ORIGIN}/founder`,
      sameAs: ["https://github.com/arhancanli"],
      affiliation: {
        "@type": "Organization",
        "@id": `${ORIGIN}/#organization`,
        name: PUBLISHER,
        url: `${ORIGIN}/`,
      },
    },
    publisher: {
      "@type": "Organization",
      "@id": `${ORIGIN}/#organization`,
      name: PUBLISHER,
      url: `${ORIGIN}/`,
      logo: { "@type": "ImageObject", url: `${ORIGIN}/brand-mark.svg` },
    },
    isPartOf: { "@type": "Periodical", name: "Canli Capital Research", url: `${ORIGIN}/research` },
    encodingFormat: "text/html",
    associatedMedia: {
      "@type": "MediaObject",
      contentUrl: `${ORIGIN}/research/${sourceFile}`,
      encodingFormat: "text/markdown",
    },
  };

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>${escapeHtml(fitTitle(shortTitle || title))}</title>
<meta name="description" content="${escapeHtml(description)}" />
<meta name="alphac-source-sha256" content="${sourceSha256}" />
${sources.length > 0 ? `<meta name="canli:sources" content="${sources.map(escapeHtml).join(" ")}" />` : ""}
<link rel="canonical" href="${url}" />
<meta name="author" content="${AUTHOR}" />
<meta name="citation_title" content="${escapeHtml(title)}" />
<meta name="citation_author" content="${AUTHOR}" />
<meta name="citation_publication_date" content="${PUBLICATION_YEAR}" />
<meta name="citation_language" content="en" />
<meta name="citation_fulltext_html_url" content="${url}" />
<meta name="robots" content="index, follow, max-snippet:-1, max-image-preview:large" />
<meta property="og:type" content="article" />
<meta property="og:site_name" content="${PUBLISHER}" />
<meta property="og:title" content="${escapeHtml(title)}" />
<meta property="og:description" content="${escapeHtml(description)}" />
<meta property="og:url" content="${url}" />
<meta property="og:image" content="${ORIGIN}/og.png" />
<meta property="article:author" content="${AUTHOR}" />
<meta name="twitter:card" content="summary_large_image" />
<meta name="twitter:title" content="${escapeHtml(title)}" />
<meta name="twitter:description" content="${escapeHtml(description)}" />
<meta name="twitter:image" content="${ORIGIN}/og.png" />
<link rel="icon" href="/favicon.svg" type="image/svg+xml" />
<link rel="icon" href="/favicon.ico" sizes="any" />
<link rel="apple-touch-icon" href="/apple-touch-icon.png" />
<link rel="preconnect" href="https://fonts.googleapis.com" />
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
<link rel="preload" as="style" href="https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;500&family=Instrument+Sans:wdth,wght@75..100,400..700&family=Newsreader:opsz,wght@6..72,300..600&display=optional" />
<link rel="stylesheet" media="print" onload="this.media='all'" href="https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;500&family=Instrument+Sans:wdth,wght@75..100,400..700&family=Newsreader:opsz,wght@6..72,300..600&display=optional" />
<noscript><link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;500&family=Instrument+Sans:wdth,wght@75..100,400..700&family=Newsreader:opsz,wght@6..72,300..600&display=optional" /></noscript>
<link rel="stylesheet" href="../css/paper.css" />
${renderProductShellStylesheet()}
<script type="application/ld+json">${JSON.stringify(jsonLd)}</script>
</head>
<body class="paper">
<a class="paper__skip" href="#content">Skip to content</a>
${renderProductShellHeader({ active: "research" })}
<main class="paper__main" id="content">
  <article class="paper__article">
    <p class="paper__eyebrow"><a href="/research">Research</a></p>
    <h1 class="paper__title">${escapeHtml(title)}</h1>
    <p class="paper__byline">By <span rel="author">${AUTHOR}</span>, ${PUBLISHER}</p>
    <div class="paper__body">
${body}
    </div>
    ${related}
    <footer class="paper__footer">
      <p class="paper__links">
        <a href="/research/${sourceFile}">Read the unrendered source</a>
        <span aria-hidden="true"> / </span>
        <a href="/research/citations/${slug}.bib" download>Cite this report</a>
        <span aria-hidden="true"> / </span>
        <a href="/open">Inspect the underlying artifacts</a>
        <span aria-hidden="true"> / </span>
        <a href="/research">All research</a>
      </p>
      <p class="paper__boundary">
        Published as evidence, not as a claim about future performance. The figures quoted here
        are reproducible from the artifacts linked above.
      </p>
    </footer>
  </article>
</main>
${renderProductShellFooter()}
</body>
</html>
`;
}

function relatedSection(paper, papers) {
  const { kind, subjects } = paper.taxonomy;
  const siblings = papers
    .filter((other) => other.slug !== paper.slug)
    .map((other) => ({
      other,
      shared: other.taxonomy.subjects.filter((s) => subjects.some((t) => t.slug === s.slug)).length,
    }))
    .filter((row) => row.shared > 0)
    .sort((a, b) => b.shared - a.shared || a.other.title.localeCompare(b.other.title))
    .slice(0, 6);

  if (!kind && !subjects.length && !siblings.length) return "";

  const hubs = [
    ...(kind ? [{ href: `/research/topics/${kind.slug}`, label: kind.label }] : []),
    ...subjects.map((s) => ({ href: `/research/topics/${s.slug}`, label: s.label })),
  ];

  const parts = [];
  if (hubs.length) {
    parts.push(`<p class="paper__related-kicker">Filed under</p>
      <p class="paper__links">${hubs
        .map((h) => `<a href="${h.href}">${escapeHtml(h.label)}</a>`)
        .join('<span aria-hidden="true"> / </span>')}</p>`);
  }
  if (siblings.length) {
    parts.push(`<p class="paper__related-kicker">Related work</p>
      <ul class="paper__related-list">${siblings
        .map(
          ({ other }) =>
            `<li><a href="/research/${other.slug}">${escapeHtml(other.title)}</a></li>`,
        )
        .join("")}</ul>`);
  }

  return `<nav class="paper__related" aria-label="Related research">
      ${parts.join("\n      ")}
    </nav>`;
}

function hubHtml(hub, members) {
  const url = `${ORIGIN}/research/topics/${hub.slug}`;
  const description = `${hub.blurb} ${members.length} published document${
    members.length === 1 ? "" : "s"
  }.`;
  const jsonLd = {
    "@context": "https://schema.org",
    "@type": "CollectionPage",
    name: `${hub.label} — ${PUBLISHER} research`,
    description: hub.blurb,
    url,
    inLanguage: "en",
    isPartOf: { "@type": "Periodical", name: "Canli Capital Research", url: `${ORIGIN}/research` },
    author: { "@type": "Person", "@id": `${ORIGIN}/#arhan-canli`, name: AUTHOR },
    publisher: { "@type": "Organization", "@id": `${ORIGIN}/#organization`, name: PUBLISHER },
    hasPart: members.map((m) => ({
      "@type": "ScholarlyArticle",
      headline: m.title,
      url: `${ORIGIN}/research/${m.slug}`,
    })),
  };

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>${escapeHtml(fitTitle(`${hub.label} research`))}</title>
<meta name="description" content="${escapeHtml(fitDescription(description))}" />
<link rel="canonical" href="${url}" />
<meta name="author" content="${AUTHOR}" />
<meta name="robots" content="index, follow, max-snippet:-1, max-image-preview:large" />
<meta property="og:type" content="website" />
<meta property="og:site_name" content="${PUBLISHER}" />
<meta property="og:title" content="${escapeHtml(hub.label)} research" />
<meta property="og:description" content="${escapeHtml(fitDescription(description))}" />
<meta property="og:url" content="${url}" />
<meta property="og:image" content="${ORIGIN}/og.png" />
<meta name="twitter:card" content="summary_large_image" />
<meta name="twitter:title" content="${escapeHtml(hub.label)} research" />
<meta name="twitter:description" content="${escapeHtml(fitDescription(description))}" />
<link rel="icon" href="/favicon.svg" type="image/svg+xml" />
<link rel="icon" href="/favicon.ico" sizes="any" />
<link rel="apple-touch-icon" href="/apple-touch-icon.png" />
<link rel="preconnect" href="https://fonts.googleapis.com" />
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
<link rel="preload" as="style" href="https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;500&family=Instrument+Sans:wdth,wght@75..100,400..700&family=Newsreader:opsz,wght@6..72,300..600&display=optional" />
<link rel="stylesheet" media="print" onload="this.media='all'" href="https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;500&family=Instrument+Sans:wdth,wght@75..100,400..700&family=Newsreader:opsz,wght@6..72,300..600&display=optional" />
<noscript><link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;500&family=Instrument+Sans:wdth,wght@75..100,400..700&family=Newsreader:opsz,wght@6..72,300..600&display=optional" /></noscript>
<link rel="stylesheet" href="../../css/paper.css" />
${renderProductShellStylesheet()}
<script type="application/ld+json">${JSON.stringify(jsonLd)}</script>
</head>
<body class="paper">
<a class="paper__skip" href="#content">Skip to content</a>
${renderProductShellHeader({ active: "research" })}
<main class="paper__main" id="content">
  <article class="paper__article">
    <p class="paper__eyebrow"><a href="/research">Research</a></p>
    <h1 class="paper__title">${escapeHtml(hub.label)}</h1>
    <p class="paper__byline">${members.length} published document${
      members.length === 1 ? "" : "s"
    } &middot; ${PUBLISHER} research, by ${AUTHOR}</p>
    <div class="paper__body">
      <p class="hub__standfirst">${escapeHtml(hub.blurb)}</p>
${(HUB_ESSAYS[hub.slug] || [])
  .map((paragraph) => `      <p>${escapeHtml(paragraph)}</p>`)
  .join("\n")}
      <h2 class="hub__heading">The ${escapeHtml(hub.label.toLowerCase())} documents</h2>
      <ul class="research-library research-library--hub">
        ${members
          .map(
            (m) =>
              `<li class="research-library__item"><a class="research-library__link" href="/research/${m.slug}"><span class="research-library__title">${escapeHtml(
                m.title,
              )}</span><span class="research-library__desc">${escapeHtml(m.description)}</span></a></li>`,
          )
          .join("")}
      </ul>
    </div>
    <footer class="paper__footer">
      <p class="paper__links"><a href="/research">All research</a><span aria-hidden="true"> / </span><a href="/open">Inspect the underlying artifacts</a></p>
      <p class="paper__boundary">Published as evidence, not as a claim about future performance.</p>
    </footer>
  </article>
</main>
${renderProductShellFooter()}
</body>
</html>
`;
}

function main() {
  if (!existsSync(SOURCE_DIR)) {
    console.error(`no research source directory at ${SOURCE_DIR}`);
    return 1;
  }
  const files = readdirSync(SOURCE_DIR).filter((name) => name.endsWith(".md")).sort();
  if (files.length === 0) {
    console.error("no research documents found; refusing to publish an empty index");
    return 1;
  }

  if (existsSync(OUT_DIR)) rmSync(OUT_DIR, { recursive: true, force: true });
  mkdirSync(OUT_DIR, { recursive: true });
  if (existsSync(CITATION_DIR)) rmSync(CITATION_DIR, { recursive: true, force: true });
  mkdirSync(CITATION_DIR, { recursive: true });

  marked.use({ gfm: true, breaks: false });

  // TWO PASSES. Classify the whole corpus first, because a paper's related-work list is a
  // function of every other paper — writing pages as they are read would give the first document
  // no siblings and the last one all of them.
  const papers = [];
  const incomplete = [];
  for (const file of files) {
    const slug = basename(file, ".md");
    const markdown = readFileSync(resolve(SOURCE_DIR, file), "utf8");
    const meta = extractMeta(markdown, slug);
    if (!meta.title || !meta.description) {
      incomplete.push({ file, title: Boolean(meta.title), description: Boolean(meta.description) });
      continue;
    }
    papers.push({
      ...meta,
      sourceFile: file,
      markdown,
      taxonomy: classify(slug, meta.title, meta.description),
    });
  }

  for (const paper of papers) {
    const body = canonicalizeRenderedResearchLinks(
      marked.parse(paper.markdown.replace(/^#\s+.*\n/, "")),
    );
    writeFileSync(
      resolve(OUT_DIR, `${paper.slug}.html`),
      pageHtml({
        ...paper,
        body,
        sourceSha256: sha256(paper.markdown),
        related: relatedSection(paper, papers),
      }),
    );
    writeFileSync(resolve(CITATION_DIR, `${paper.slug}.bib`), bibtex(paper));
  }
  const archivalPapers = archivalPaperRoutes();

  const hubs = [];
  mkdirSync(resolve(OUT_DIR, "topics"), { recursive: true });
  for (const hub of [...KINDS, ...SUBJECTS]) {
    const members = papers
      .filter((paper) =>
        KINDS.includes(hub)
          ? paper.taxonomy.kind === hub
          : paper.taxonomy.subjects.some((s) => s.slug === hub.slug),
      )
      .sort((a, b) => a.title.localeCompare(b.title));
    // A hub with fewer than three members is a page that exists to hold links, which is the one
    // thing this must not become.
    if (members.length < 3) continue;
    writeFileSync(resolve(OUT_DIR, "topics", `${hub.slug}.html`), hubHtml(hub, members));
    hubs.push({ ...hub, count: members.length });
  }

  writeFileSync(
    resolve(ROOT, "public/research-index.json"),
    `${JSON.stringify(
      {
        generated_by: "scripts/build-papers.mjs",
        count: papers.length,
        topics: hubs.map((hub) => ({
          slug: hub.slug,
          label: hub.label,
          count: hub.count,
          path: `/research/topics/${hub.slug}`,
          blurb: hub.blurb,
        })),
        papers: papers.map(({ slug, title, description, sourceFile }) => ({
          slug,
          title,
          description,
          author: AUTHOR,
          publication_year: PUBLICATION_YEAR,
          citation_key: citationKey(slug),
          path: `/research/${slug}`,
          source_path: `/research/${sourceFile}`,
          citation_path: `/research/citations/${slug}.bib`,
        })),
        archival_papers: archivalPapers.map(({ title, route, originalRoute }) => ({
          title,
          path: route,
          original_path: originalRoute,
        })),
      },
      null,
      2,
    )}\n`,
  );

  // The library page must link the taxonomy it publishes. Until 2026-08-22 it linked eleven
  // papers and ZERO hubs, so four hubs and their exclusive members sat four and five clicks from
  // the homepage — reachable only by chance, through another paper's related-work section. The
  // block is generated from the hubs actually rendered, so it cannot drift from the corpus, and
  // the sentinels are asserted: a silent no-op here would restore the defect invisibly.
  const libraryPage = resolve(ROOT, "research.html");
  const libraryHtml = readFileSync(libraryPage, "utf8");
  const hubsMarkup = hubs
    .map(
      (hub) =>
        `        <a href="/research/topics/${hub.slug}" class="research-link label">` +
        `${escapeHtml(hub.label)} <span class="research-hubs__n mono-label">` +
        `${hub.count}</span></a>`,
    )
    .join("\n");
  const block = `<!-- HUBS:START -->\n${hubsMarkup}\n        <!-- HUBS:END -->`;
  const withHubs = libraryHtml.replace(
    /<!-- HUBS:START -->[\s\S]*?<!-- HUBS:END -->/,
    block,
  );
  if (withHubs === libraryHtml && !libraryHtml.includes(block)) {
    throw new Error(
      "research.html has no HUBS:START/HUBS:END sentinels — the topic links would silently " +
        "stop being generated and the hubs would go back to being four clicks deep",
    );
  }
  const archivalMarkup = archivalPapers
    .map(
      (paper) =>
        `        <a href="${paper.route}" class="research-link label">` +
        `${escapeHtml(paper.title)}</a>`,
    )
    .join("\n");
  const archivalBlock =
    `<!-- ARCHIVAL_PAPERS:START -->\n${archivalMarkup}\n` +
    `        <!-- ARCHIVAL_PAPERS:END -->`;
  const rewritten = withHubs.replace(
    /<!-- ARCHIVAL_PAPERS:START -->[\s\S]*?<!-- ARCHIVAL_PAPERS:END -->/,
    archivalBlock,
  );
  if (rewritten === withHubs && !withHubs.includes(archivalBlock)) {
    throw new Error("research.html has no archival-paper sentinels");
  }
  writeFileSync(libraryPage, rewritten);

  const today = new Date().toISOString().slice(0, 10);
  const urls = [
    ...STATIC_ROUTES.map((route) => ({ ...route, loc: `${ORIGIN}${route.path}` })),
    ...hubs.map((hub) => ({
      loc: `${ORIGIN}/research/topics/${hub.slug}`,
      priority: "0.8",
      changefreq: "weekly",
    })),
    ...papers.map((paper) => ({
      loc: `${ORIGIN}/research/${paper.slug}`,
      priority: "0.7",
      changefreq: "monthly",
    })),
    ...archivalPapers,
    // The measurement pages, DERIVED from what build-measurements.mjs put on disk. Listing them
    // here by hand would reintroduce exactly the defect this file's header describes: a sitemap
    // that stops matching the pages long before anyone notices.
    ...measurementRoutes(),
    ...trialRoutes(),
  ];
  writeFileSync(
    resolve(ROOT, "public/sitemap.xml"),
    `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls
  .map(
    (url) =>
      `  <url>\n    <loc>${url.loc}</loc>\n    <lastmod>${today}</lastmod>\n` +
      `    <changefreq>${url.changefreq}</changefreq>\n    <priority>${url.priority}</priority>\n  </url>`,
  )
  .join("\n")}
</urlset>
`,
  );

  console.log(`rendered ${papers.length} research pages -> research/*.html`);
  console.log(`rendered ${hubs.length} topic hubs -> research/topics/*.html`);
  for (const hub of hubs) console.log(`    ${hub.label.padEnd(32)} ${hub.count}`);
  console.log(`sitemap: ${urls.length} URLs`);
  if (incomplete.length) {
    console.log("\nSkipped for missing metadata (NOT invented):");
    for (const item of incomplete) {
      console.log(`  ${item.file}  title=${item.title} description=${item.description}`);
    }
  }
  return 0;
}

process.exit(main());
