import test from 'node:test';
import { buildCompanyRelease } from './build-company-release.mjs';
import assert from 'node:assert/strict';
import { mkdtempSync, readFileSync, writeFileSync, rmSync } from 'node:fs';
import { resolve } from 'node:path';
import { tmpdir } from 'node:os';
import { once } from 'node:events';
import { gunzipSync } from 'node:zlib';
import { refreshCandidates } from './refresh-company-candidates.mjs';
import { stageCompanyDelivery } from './stage-company-delivery.mjs';
import { buildCompanyCatalog } from './lib/build-company-catalog.mjs';
import { buildCompanyAssets } from './lib/company-assets.mjs';
import { companyPreviewServer } from './lib/company-preview-server.mjs';

test('source delivery preserves original bytes, fails closed on corruption, and retains prior manifest after rejected staging', async t => {
  const root = mkdtempSync(resolve(tmpdir(), 'canli-delivery-'));
  t.after(() => rmSync(root, { recursive: true, force: true }));
  const record = JSON.parse(readFileSync('public/company-data/0000029534.json'));
  const raw = gunzipSync(readFileSync('public' + record.source_snapshot));
  const input = resolve(root, 'captures'), output = resolve(root, 'delivery'), catalogDir = resolve(root, 'catalog');
  await refreshCandidates({ ciks: [record.cik], output: input, fetcher: async () => new Response(raw), now: () => '2026-09-19T12:00:00Z', pause: async () => {} });
  writeFileSync(resolve(input, 'ciks.json'), JSON.stringify([record.cik]));
  const delivery = stageCompanyDelivery(input, output);
  const selected = JSON.parse(readFileSync(resolve(input, record.cik + '.record.json')));
  buildCompanyCatalog([selected], catalogDir);
  const sourceHtml = readFileSync('companies/0000029534.html', 'utf8');
  writeFileSync(resolve(root, 'company-page-assets.json'), JSON.stringify(buildCompanyAssets(sourceHtml, '<link rel="stylesheet" href="/assets/company.css">')));
  const { server } = companyPreviewServer({ catalogDir, deliveryDir: output, distDir: root });
  server.listen(0, '127.0.0.1'); await once(server, 'listening');
  t.after(async () => { server.closeAllConnections(); await new Promise(resolve => server.close(resolve)); });
  const base = `http://127.0.0.1:${server.address().port}`;
  const descriptor = delivery.files[0].source;
  const original = readFileSync(resolve(input, selected.source_sha256 + '.json.gz'));
  assert.deepEqual(Buffer.from(await (await fetch(base + descriptor.path)).arrayBuffer()), original);
  const release = await buildCompanyRelease(catalogDir, output);
  assert.equal(release.companies, 1); assert.equal(release.publication_approved, false);
  const priorRelease = readFileSync(resolve(output, 'company-release.json'));
  const manifest = readFileSync(resolve(output, 'delivery.json'));
  writeFileSync(resolve(output, descriptor.storage_path), 'corrupt');
  assert.equal((await fetch(base + descriptor.path)).status, 503);
  assert.throws(() => stageCompanyDelivery(input, output), /corrupt/);
  await assert.rejects(buildCompanyRelease(catalogDir, output), /corruption/);
  assert.deepEqual(readFileSync(resolve(output, 'company-release.json')), priorRelease);
  assert.deepEqual(readFileSync(resolve(output, 'delivery.json')), manifest);
  assert.equal((await fetch(base + '/companies/0000029534/overview')).status, 404);
  assert.equal((await fetch(base + '/companies/page/1', { redirect: 'manual' })).status, 308);
});
